---
# This service is deliberately empty, and updated via an EndpointSlice
# as part of the benchmark process.
# DPDK interfaces do not have an IP visible to K8s by default
# https://kubernetes.io/docs/concepts/services-networking/endpoint-slices/
apiVersion: v1
kind: Service
metadata:
  name: aeron-benchmark-md
  labels:
    app: aeron-benchmark
spec:
  ports:
    - port: 10000
      name: aeron
  clusterIP: None
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aeron-benchmark
data:
  # Only used with DPDK at present, as the java-md/benchmark code ships with it's own
  # version of this file
  low-latency-driver.properties: |
    aeron.dir.delete.on.start=true
    aeron.dir.delete.on.shutdown=true
    aeron.print.configuration=true
    aeron.term.buffer.sparse.file=true
    aeron.pre.touch.mapped.memory=false
    aeron.perform.storage.checks=false
    aeron.socket.so_sndbuf=2m
    aeron.socket.so_rcvbuf=2m
    aeron.rcv.initial.window.length=2m
    aeron.threading.mode=DEDICATED
    aeron.conductor.idle.strategy=noop
    aeron.sender.idle.strategy=noop
    aeron.receiver.idle.strategy=noop
    aeron.spies.simulate.connection=true
    aeron.use.windows.high.res.timer=true
    agrona.disable.bounds.checks=true
    aeron.driver.timeout=30000
    aeron.dir=/dev/shm/aeron
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aeron-benchmark-envs
data:
  TEST_OUTPUT_PATH: /dev/shm/results
  NODE0_ADDRESS: aeron-benchmark-0.aeron-benchmark-md
  NODE1_ADDRESS: aeron-benchmark-1.aeron-benchmark-md
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aeron-benchmark-envs-dpdk
data:
  AERON_DPDK_THREADS_FROM_CGROUP: "TRUE"
  AERON_DPDK_TX_MEMPOOL_PER_QUEUE: "true"
  AERON_DPDK_TX_MEMPOOL_OPS: "ring_mp_mc"
  AERON_DPDK_TX_MEMPOOL_CACHE_SIZE: "512"
  AERON_DPDK_RX_MEMPOOL_OPS: "ring_mp_mc"
  AERON_DPDK_RX_MEMPOOL_CACHE_SIZE: "512"
---
apiVersion: v1
kind: Pod
metadata:
  name: aeron-benchmark-0
# Populated throught base-containers.yml kustomization
---
apiVersion: v1
kind: Pod
metadata:
  name: aeron-benchmark-1
# Populated throught base-containers.yml kustomization
