---
# Update tolerations and nodeselectors
apiVersion: v1
kind: Pod
metadata:
  name: all
spec:
  tolerations:
    # Select our special benchmark nodes
    - key: "dpdk"
      operator: "Exists"
  # Select our special benchmark nodes
  nodeSelector:
    purpose: "dpdk"

  containers:
    - name: benchmark
      image: <insert_benchmark_image_repo_here>
      imagePullPolicy: Always

    - name: aeronmd-dpdk
      image: <insert_aeronmd_dpdk_image_repo_here>
      imagePullPolicy: Always
      resources:
        limits:
          # Give us a DPDK NIC through https://github.com/AdaptiveConsulting/k8s-dpdk-mgr
          intel.com/aws_dpdk: "1"
